apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
